name: 'Veracode SCA'
description: 'Roda o Veracode Software Composition Analysis (SCA) em background usando o agente oficial.'

inputs:
  veracode_sca_token:
    description: 'Token de API do Veracode SCA (mapeado para SRCCLR_API_TOKEN).'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Rodar Veracode SCA
      id: run_sca
      shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ inputs.veracode_sca_token }}
      run: |
        set -euo pipefail

        if [ -z "${SRCCLR_API_TOKEN:-}" ]; then
          echo "Erro: veracode_sca_token nao foi fornecido." >&2
          exit 1
        fi

        set +e
        curl -sSL https://sca-downloads.veracode.com/ci.sh | bash -s -- scan --allow-dirty 2>&1 | tee veracode_sca.log
        SCA_EXIT=${PIPESTATUS[1]}
        set -e

        if [ "${SCA_EXIT}" -ne 0 ]; then
          echo "Aviso: Veracode SCA retornou exit code ${SCA_EXIT} (o job continua)." >&2
        fi
