name: Security Scan (Auto Packager + Baseline + IaC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Auto Packager + Baseline + IaC
        uses: Afrika-Tecnologia/Veracode-Connect@v1
        with:
          portal_afrika_api_key: ${{ secrets.PORTAL_AFRIKA_API_KEY }}
          baseline_mode: 'portal_afrika'
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          enable_auto_packager: 'true'
          enable_upload_scan: 'false'
          policy_fail: 'false'
          enable_iac: 'true'


