name: Security Scan (Upload & Scan Only + Auto Packager + IaC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload & Scan + IaC (auto packager)
        uses: JuanCunhaa/Veracode-Integration-Helper@v1
        with:
          veracode_api_id: ${{ secrets.VERACODE_API_ID }}
          veracode_api_key: ${{ secrets.VERACODE_API_KEY }}
          enable_auto_packager: 'true'
          enable_pipelinescan: 'false'
          enable_baseline: 'false'
          enable_upload_scan: 'true'
          veracode_sandbox: 'true'
          enable_iac: 'true'


