name: 'Veracode IaC'
description: 'Roda o Veracode Container/IaC/Secrets scanning (directory scan) e imprime o resultado no console.'

inputs:
  veracode_api_id:
    description: 'ID da API do Veracode (VID).'
    required: true
  veracode_api_key:
    description: 'Key da API do Veracode (VKEY).'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Veracode Container/IaC/Secrets scan (directory)
      id: iac_scan
      continue-on-error: true
      uses: veracode/container_iac_secrets_scanning@v1.0.6
      with:
        vid: ${{ inputs.veracode_api_id }}
        vkey: ${{ inputs.veracode_api_key }}
        github-token: ${{ github.token }}
        command: scan
        type: directory
        source: .
        format: table
        fail_build: 'false'
        fail_build_on_error: 'false'
